### ISSUE TITLE
[QA] Perform functional testing

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-invoices#1]
# Context

New app, replacement of invoices plugin, available here
- https://invoices.saleor.app/
- https://invoices.staging.saleor.app/

# Usage

- install with `https://invoices.saleor.app/api/manifest` (dashboard -> apps -> install with manifest and use this link)
- go to order in dashboard
- click "generate invoice"

# Features
- App should provide configuration screen with address form - per channel
- default address data should be fetched from shop info (dashboard preferences)
- each form can be edited separately, so each channel can provide its own billing address on the invoice
- generated invoice should have proper order data, client data and channel address data

# Scope of testing

Features above & general business testing - how different orders behave, how shipping, discounts, vouchers etc behave

# Known problems

https://github.com/saleor/saleor-dashboard/issues/2908

**Comment by michalina-graczyk** [comment]
Bugs found:
Unknown action type and response timeout
Steps:
1. Install saleor app invoice in Apps
2. Click into that app
Results:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/25908728/211534503-29f3751f-f7c8-4b5c-96f1-7af62ebad886.png">

**Comment by michalina-graczyk** [comment]
Sending invoices is not working
1.Install saleor app invoice in Apps
2. Go to orders
3. Select random order -> https://master.staging.saleor.cloud/dashboard/orders/T3JkZXI6MTg0NDE0NjktNTYyYy00Njc1LTg2ZWYtMDc4NTY3NGM1ZThj
4. Click 'generate invoice'
5. Select Invoice `Invoice 1/5/2023`
6. Click `send`
Error on the screen:
![Image](https://user-images.githubusercontent.com/25908728/211545313-d9a60596-0719-411e-9baa-548b05698210.png)

**Comment by michalina-graczyk** [comment]
Small differences in the invoice


![Image](https://user-images.githubusercontent.com/25908728/211547714-8e828fdc-611f-4dd1-a842-163540f88167.png)

**Comment by michalina-graczyk** [comment]
Unfilled & unpaid order have "paid" invoice




![Image](https://user-images.githubusercontent.com/25908728/211563472-e9573d73-b747-4b0f-bd32-66eeceefff0d.png)



![Image](https://user-images.githubusercontent.com/25908728/211563514-de7150d4-1156-42a7-bbcb-ed64aefdb520.png)

**Comment by lkostrowski** [comment]
> Bugs found: Unknown action type and response timeout Steps:
> 
> 1. Install saleor app invoice in Apps
> 2. Click into that app
>    Results:
> 
> <img alt="image" width="1293" src="https://user-images.githubusercontent.com/25908728/211534503-29f3751f-f7c8-4b5c-96f1-7af62ebad886.png">

this one is not related to Invoices app, its old, minor problem with AppBridge, there is a ticket for that

Other issues are reported to Dashboard

Last issue -> will solve by changing "paid" to "total amount"

**Comment by lkostrowski** [comment]
Issues from first test round should be fixed. 

One issue is still open but its not scope of this app (https://github.com/saleor/saleor-dashboard/issues/2972)

Can be re-tested

**Comment by michalina-graczyk** [comment]
Retsted:
Unknown action type and response timeout -> this issue still exist. Rests looks fine


![Image](https://user-images.githubusercontent.com/25908728/214823789-934cd71e-c935-4770-85dc-1c89a46b01c6.png)

**Comment by lkostrowski** [comment]
Fine, this error is unrelated, so closing
